spring:
  application:
    name: ms-student
    datasource:
      url: jdbc:postgresql://db.gnlymwkcxahulaolbbbe.supabase.co:5432/postgres
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: EducationDev@123
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true

logging:
  level:
    web: debug

springdoc:
  api-docs:
    path: /api-docs
